include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
    - test/**.mocks.dart
    - lib/firebase_options**.dart

linter:
  rules:
    no_default_cases: false
    one_member_abstracts: false
    public_member_api_docs: false
    require_trailing_commas: false
